[package]
name = "alexandrie"
version = "0.1.0"
authors = ["Nicolas Polomack <nicolas.polomack@its-future.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json", "diesel_mysql_pool"] }
git2 = "0.9.1"
serde = { version = "1.0.94", features = ["derive"] }
json = { package = "serde_json", version = "1.0.40" }
semver = { version = "0.9.0", features = ["serde"] }
diesel = { version = "1.4.2", features = ["mysql", "chrono"] }
chrono = { version = "0.4.7", features = ["serde"] }
sha2 = "0.8.0"
byteorder = "1.3.2"
