[package]
name = "alexandrie"
version = "0.1.0"
authors = ["Nicolas Polomack <nicolas@polomack.eu>"]
description = "An alternative crate registry, implemented in Rust."
repository = "https://github.com/Hirevo/alexandrie"
documentation = "https://crates.polomack.eu/docs/alexandrie"
edition = "2018"
default-run = "alexandrie"

[dependencies]
rocket = "0.4.1"
serde = { version = "1.0.94", features = ["derive"] }
json = { package = "serde_json", version = "1.0.40" }
semver = { version = "0.9.0", features = ["serde"] }
diesel = { version = "1.4.2", features = ["mysql", "chrono", "numeric"] }
chrono = { version = "0.4.7", features = ["serde"] }
sha2 = "0.8.0"
byteorder = "1.3.2"
hex = "0.3.2"
toml = "0.4.10"
bigdecimal = { version = "0.0.14", features = ["serde"] }
handlebars = "1.1.0"
num-format = "0.4.0"
syntect = "3.2.0"
cmark = { package = "pulldown-cmark", version = "0.5.2" }
flate2 = "1.0.9"
tar = "0.4.26"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "serve", "diesel_mysql_pool", "handlebars_templates"]
