[package]
name = "alexandrie"
version = "0.1.0"
edition = "2018"
authors = ["Nicolas Polomack <nicolas@polomack.eu>"]
description = "An alternative crate registry, implemented in Rust."
repository = "https://github.com/Hirevo/alexandrie"
documentation = "https://crates.polomack.eu/docs/alexandrie"

default-run = "alexandrie"

[dependencies]
rocket = { version = "0.4.1" }
serde = { version = "1.0.94", features = ["derive"] }
json = { package = "serde_json", version = "1.0.40" }
diesel = { version = "1.4.2", features = ["mysql", "chrono", "numeric"] }
semver = { version = "0.9.0", features = ["serde"] }
chrono = { version = "0.4.7", features = ["serde"] }
sha2 = { version = "0.8.0" }
byteorder = { version = "1.3.2" }
hex = { version = "0.3.2" }
toml = { version = "0.4.10" }
syntect = { version = "3.2.0" }
cmark = { package = "pulldown-cmark", version = "0.5.2" }
flate2 = { version = "1.0.9" }
tar = { version = "0.4.26" }

handlebars = { version = "1.1.0", optional = true }
num-format = { version = "0.4.0", optional = true }
bigdecimal = { version = "0.0.14", features = ["serde"], optional = true }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "serve", "diesel_mysql_pool", "handlebars_templates"]

[features]
default = ["frontend"]
frontend = ["handlebars", "num-format", "bigdecimal"]
