[package]
name = "alexandrie"
version = "0.1.0"
edition = "2018"
authors = ["Nicolas Polomack <nicolas@polomack.eu>"]
description = "An alternative crate registry, implemented in Rust."
repository = "https://github.com/Hirevo/alexandrie"
documentation = "https://crates.polomack.eu/docs/alexandrie"
keywords = ["crates", "cargo", "web", "registry"]

default-run = "alexandrie"

[dependencies]
# essential
tide =  { git = "https://github.com/rustasync/tide", branch = "master" }
runtime = { version = "0.3.0-alpha.6" }
runtime-tokio = { version = "0.3.0-alpha.5" }
diesel = { version = "1.4.2", features = ["r2d2", "mysql", "chrono", "numeric"] }
serde = { version = "1.0.94", features = ["derive"] }
json = { package = "serde_json", version = "1.0.40" }
toml = { version = "0.4.10" }
semver = { version = "0.9.0", features = ["serde"] }
chrono = { version = "0.4.7", features = ["serde"] }
sha2 = { version = "0.8.0" }
byteorder = { version = "1.3.2" }
hex = { version = "0.3.2" }
bytes = { version = "0.4.12" }

# async primitives
tokio = { git = "https://github.com/tokio-rs/tokio", branch = "master" }
tokio-threadpool = { version = "0.1.15" }
futures_01 = { package = "futures", version = "0.1.28" }
futures-preview = { version = "0.3.0-alpha.17", features = ["compat", "nightly", "async-await"] }

# README rendering
syntect = { version = "3.2.0" }
cmark = { package = "pulldown-cmark", version = "0.5.2" }
flate2 = { version = "1.0.9" }
tar = { version = "0.4.26" }

# frontend
handlebars = { version = "1.1.0", optional = true }
num-format = { version = "0.4.0", optional = true }
bigdecimal = { version = "0.0.14", features = ["serde"], optional = true }

# logs
env_logger = { version = "0.6.2" }

# miscellaneous
path-absolutize = { version = "1.1.6" }

[features]
default = ["frontend"]
frontend = ["handlebars", "num-format", "bigdecimal"]
