[global.databases.alexandrie]
url = "mysql://alexandrie:egypt@localhost:3306/alexandrie"

[global.crate-index]
type = "cli"
path = "crate-index"

[global.crate-storage]
type = "disk"
path = "crate-storage"

[global.frontend]
enabled = true
title = "crates.polomack.eu"
description = "My personal Rust crate registry for my personal projects"
# favicon = ""
