version: "3.7"
services:
  index:
    image: jkarlos/git-server-docker:latest
    volumes:
      - ./index/repos:/git-server/repos
    expose:
      - "22"
    secrets:
      - source: git_ssh_pubkey
        target: /git-server/keys/id_rsa.pub
  registry:
    build:
      context: ../..
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DATABASE=${DATABASE}
    image: alexandrie-e2e-${DATABASE}:0.1
    environment:
      CRATE_INDEX: git@index:/git-server/repos/index.git
      DATABASE: ${DATABASE}
      GIT_NAME: Alexandrie E2E Tester
      GIT_EMAIL: nicolas@polomack.eu
      APPDATA: /home/alex/appdata
    ports:
      - "3000:3000"
    volumes:
      - ../../docker/${DATABASE}/alexandrie.toml:/home/alex/alexandrie.toml
      - ./keys:/home/alex/.ssh
    depends_on:
      - index
  runner:
    build:
      context: .
      dockerfile: ./runner/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    image: alexandrie-e2e-runner:0.1
    volumes:
      - "../scenarios/${SCENARIO}:/home/runner/original"
      - "./keys/id_rsa:/home/runner/.ssh/id_rsa"
    depends_on:
      - registry
secrets:
  git_ssh_key:
    file: ./keys/id_rsa
  git_ssh_pubkey:
    file: ./keys/id_rsa.pub
