#
# This is an expansion upon the main `docker-compose.yaml` file.
# It applies additional configuration to spawm a MySQL database.
#

version: "3.7"
services:
  # append to existing `registry` service (defined in `docker-compose.yaml`).
  registry:
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
